spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iTrust2_production?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000 
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

server:
  port: 7719
  servlet:
    contextPath: /iTrust2
